### ISSUE TITLE
Linked survey in README is closed

### ISSUE THREAD

**Issue by arthurzenika** [ContainerOrchestration/Labs#11]
https://fr.surveymonkey.com/r/6DCVNNF says This survey is currently closed.

**Comment by mjbright** [comment]
Hi, thanks for your issue.

Yes that Survey referred to a previous run of the tutorial, sorry about that.

I'll provide another means for Pyconfr Oct 2018 attendees to provide feedback.
Mail about to be sent to those attendees.
